---
- name: My First Ansible Playbook
  hosts: localhost
  connection: local
  become: true
  
  tasks:
    - name: Ensure my Projects folder exists
      file:
        path: /home/{{ ansible_env.SUDO_USER }}/Ansible/k8s-projects
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"
        state: directory
        mode: '0755'

    - name: Create a simple MOTD (Message of the Day)
      copy:
        content: "Property of a soon to be pro K8s Engineer. Don't touch the Macbook!\n"
        dest: /home/{{ ansible_env.SUDO_USER }}/Ansible/k8s-projects/welcome.txt

    - name: Setup Brave Browser
      include_tasks: install_brave.yml

    - name: Install essential terminal utils
      include_tasks: utils.yml

    - name: Install docker
      include_tasks: install_docker.yml

    - name: Install Terraform
      include_tasks: install_terraform.yml
      
    - name: Install k3d
      include_tasks: install_k3d.yml
      
    - name: Install kubectl
      include_tasks: install_k3d_kubectl.yml
      
    - name: Install k9s
      include_tasks: install_k3d_k9s.yml

    - name: Config k9s
      include_tasks: config_k3d_k9s.yml

    - name: Install Lens
      include_tasks: install_lens.yml

    - name: Deploy NginX
      include_tasks: deploy_nginx.yml

    - name: Create Loadbalancer
      include_tasks: create_loadbalancer.yml
