- name: Install htop
  become: true
  apt:
    name:
      - htop
    state: present
    
- name: Install Kubernetes Python library via Apt
  become: true
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present
