- name: Install htop
  become: true
  apt:
    name:
      - htop
    state: present

- name: Install Kubernetes Python library via Apt
  become: true
  ansible.builtin.apt:
    name: 
      - btop
      - python3-kubernetes
    state: present

- name: Add VS Code GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: 📦 Add VS Code Repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
    state: present

- name: 💻 Install VS Code
  become: true
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: yes
