apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.name }}-deployment
spec:
  replicas: {{ .values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.name }}
    spec:
      containers:
        - name: nginx
          image: "{{ .values.image.repository }}:{{ .values.image.tag }}"
          ports:
            - containerPort: 80
