apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .values.service.name }}
            port:
              number: {{ .values.service.port }}
